# Generated by Django 4.2.7 on 2023-11-13 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petseeker',
            name='phone_num',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petseeker',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pet_seeker_pics/'),
        ),
        migrations.AddField(
            model_name='petseeker',
            name='pref',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='petshelter',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pet_seeker_pics/'),
        ),
    ]
